"""Run verification Scenario 1 (simple conversion) using the ab_framework.

This script is intentionally small so we can compare the amount of
user-written code needed when using the framework vs direct scipy/owl usage.

It reuses the existing Scenario 1 data and ground-truth logic from
`verification.data_generator` and `verification.ground_truth`.
"""

from pathlib import Path

import pandas as pd

from ab_framework import ABTestFramework
from verification import ground_truth


def load_scenario1() -> pd.DataFrame:
    """Load Scenario 1 conversion data as a single DataFrame.

    We rely on the existing CSV generated by `verification/data_generator.py`.
    """

    here = Path(__file__).resolve().parent
    data_path = here / "data" / "scenario1_conversion.csv"
    return pd.read_csv(data_path)


def conversion_metric(df: pd.DataFrame) -> float:
    """Simple user-level conversion metric.

    The framework will aggregate to user level; here we just expose a
    per-row conversion flag that will be aggregated via max() per user.
    """

    return float(df["converted"].max())


def run_scenario1_with_framework() -> None:
    """Run Scenario 1 using the framework and print a small summary."""

    df = load_scenario1()

    # Minimal configuration sketch; in a real integration, data_sources
    # would point to your storage/query layer. Here we operate on df
    # directly for simplicity.
    config = {
        "experiment": {
            "name": "scenario1_conversion_framework",
            "alpha": 0.05,
            "unit_id": "user_id",
            "metric": "conversion",
        }
    }

    framework = ABTestFramework(config=config, metric_fn=conversion_metric)
    results = framework.get_latest_analysis(df=df, variant_column="variant")

    print("=== Scenario 1 with framework ===")
    print(
        {
            "p_value": results.get("p_value"),
            "lift": results.get("lift"),
            "decision": results.get("decision"),
        }
    )

    # Optional: compare to ground truth to sanity-check
    gt = ground_truth.compute_scenario1()
    print("=== Ground truth (scipy) ===")
    print({"p_value": gt["p_value"], "lift": gt["lift"]})


if __name__ == "__main__":
    run_scenario1_with_framework()
